name: CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Windows Desktop
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Examples\WindowsDesktop\WindowsDesktop_VS2019.sln -p:Configuration=Release
        rm $Env:GITHUB_WORKSPACE\Examples\WindowsDesktop\obj -r -fo
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r $Env:GITHUB_WORKSPACE\..\UniversalRobotsSDK_UnderAutomation.zip $Env:GITHUB_WORKSPACE
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "$Env:GITHUB_WORKSPACE/../UniversalRobotsSDK_UnderAutomation.zip"
        bodyFile: "whatsNew.md"
        token: ${{ secrets.GITHUB_TOKEN }}
